CREATE TABLE courses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    start_date  TIMESTAMP WITHOUT TIME ZONE,
    teacher_id  BIGINT,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE enrollments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT,
    course_id  BIGINT,
    CONSTRAINT pk_enrollments PRIMARY KEY (id)
);

CREATE TABLE students
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    major   VARCHAR(255),
    course  VARCHAR(255),
    email   VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE students
    ADD CONSTRAINT uc_students_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE courses
    ADD CONSTRAINT FK_COURSES_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES users (id);

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);